### ISSUE TITLE
Project lay out

### ISSUE THREAD

**Issue by LodeVlaeminck** [GamingAnonymous/TornCityAPISharp#13]
I have an issue with the layout of our model:

Currently we have Created a new namespace for every Method, I think we should stick to 1 name space per API section. Like a namespacec for User where we contain all the User models (Basic, Stats, ...).

this can cause some issues later on (models with same names and different props), but this can be fixed as we run into this issue.

**Comment by CarlHalstead** [comment]
I definitely agree. I feel it would make it easier to develop in the end.
