### ISSUE TITLE
How would I check if there are no events?

### ISSUE THREAD

**Issue by CarlHalstead** [GamingAnonymous/TornCityAPISharp#17]
Tested a little and the exception is no longer caused.
So at the moment I am trying to get a message to display if there are no events. How would I check this?
@LodeVlaeminck I tried
```c#
if (playerEvents.events == null)
{
	Console.WriteLine("You have no events");
	return;
}
```

```c#
if (playerEvents == null)
{
	Console.WriteLine("You have no events");
	return;
}
```
I also tried this one below, but it caused an exception

```c#
if (playerEvents.events.Count <= 0)
{
	Console.WriteLine("You have no events");
	return;
}
```
```
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Additional information: Exception has been thrown by the target of an invocation.
```

**Comment by LodeVlaeminck** [comment]
I am missing a bit of context here. Which api method did you call ? And do you want this to be a part of this project ?

**Comment by CarlHalstead** [comment]
haha sorry. I meant I was just curious from the end-developers stand point. Lets imagine there were no events so I wanted to display a message telling the user that there were no events. How would I check this. 
Its not something that needs to be in the API, I could however put it in the wiki.

**Comment by CarlHalstead** [comment]
Heres a little more code.
```c#
API api = new API("MyAPIKey");
PlayerStatistics player;

private void Form1_Load(object sender, EventArgs e)
{
	player = new PlayerStatistics(ref api);
	faction = new FactionStatistics(ref api);
}

private async void PlayerEvents()
{
	var playerEvents = await player.GetPlayerEvents();

	if (playerEvents.events.Count == 0)
	{
		Console.WriteLine("You have no events");
		return;
	}

	foreach (KeyValuePair<long, Event> key in playerEvents.events)
		Console.WriteLine(key.Value.EventText);
}
```

**Comment by LodeVlaeminck** [comment]
Oké , It is really strange that you dont have any events in that object. I guess there is a deeper problem in the mapping to the event object. Will look into it.

The way you call the api is from an older version. I have changed the way an api is called quite a bit.

        [TestMethod]
        public async Task TestFactionBasic()
        {
            TornApiWrapper wrapper = new TornApiWrapper(apiKey, 50);
            var test = await wrapper.GetFromFactionApi<FactionBasic>("");

            Assert.IsNotNull(test, "Test Object is not null");
            Assert.AreEqual(string.IsNullOrWhiteSpace(test.FactionID.ToString()), false);
            Assert.AreEqual(wrapper.ApiKey.ApiCallCount, 1);
        }

First of all you should use the TornApiWrapper to do the api calls for you.

Calling the Api gets really easy, all you  have to do is tell the method what object you expect to be returned. The name of this object is always FieldMethod e.g. FactionBasic or FactionNews.

Then all you have to do is wait for the response. 

this works for the following fields: Faction, Company, Property => up next is Player Item and Torn.

**Comment by CarlHalstead** [comment]
Ok thanks. yeah I had a quick look through before and assumed I was supposed to use it like that. I will update my example tests.

**Comment by LodeVlaeminck** [comment]
Yhea But it will not work for the player api :)

**Comment by CarlHalstead** [comment]
;)

**Comment by LodeVlaeminck** [comment]
Player APi is now online, this will need a lot of testing
