### ISSUE TITLE
Easy way to find property ID?

### ISSUE THREAD

**Issue by CarlHalstead** [GamingAnonymous/TornCityAPISharp#19]
I was just testing around with the latest version and with the property api section. While trying to find the ID of properties I was thinking is there an easier way to find them or would it be possible to call them by name? I am just curious.
A quick Google search reveals no meaningful results.
[https://www.google.co.uk/search?q=torn+city+property+id&gws_rd=cr&ei=lz9mWOfQJJXmwAKfwJCABg](https://www.google.co.uk/search?q=torn+city+property+id&gws_rd=cr&ei=lz9mWOfQJJXmwAKfwJCABg)

**Comment by CarlHalstead** [comment]
Should also note that if the property ID is incorrect then it will cause an exception.

**Comment by LodeVlaeminck** [comment]
Yes, This error is because the api returns an error json. This can not be mapped to a Property object => the reason it fails. But when bad parameters are provided it is correct that an error is throw (IMO).


The only way to get a property id is from the player API.

**Comment by CarlHalstead** [comment]
I will close this as there is not an easy way.
