### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by LodeVlaeminck** [GamingAnonymous/TornCityAPISharp#23]
Hello,

With only 1 bug to fix (the api call counter). I have added this package to nuget for easy installation.

PM> Install-Package TornCityAPISharp 

To add it to you project, I have tried it for 4.6 and 4.5.2 and it seem to work. Not working for dot net core (because of the JSON.net dependency)

**Comment by CarlHalstead** [comment]
Ok thanks, I will add it to the readme and the Wiki.
