### ISSUE TITLE
Updating Wiki info

### ISSUE THREAD

**Issue by LodeVlaeminck** [GamingAnonymous/TornCityAPISharp#24]
I am not able to update the wiki info. A guide on how to call the api will be use full

**Comment by CarlHalstead** [comment]
I sent you an invite to collaborate on the project. Feel free to update the wiki if needed. Over the next couple of days I will tidy up this GitHub project a little.

**Comment by LodeVlaeminck** [comment]
I will try to solve the api - call counter. Then we can do the beta release. There are going to be some bugs for sure. But dont have time to do all the testing

**Comment by LodeVlaeminck** [comment]
Api call count is solved.
