### ISSUE TITLE
New APi Methods

### ISSUE THREAD

**Issue by LodeVlaeminck** [GamingAnonymous/TornCityAPISharp#27]
New Api methods have been added in Faction and General. Model need to be created

**Comment by CarlHalstead** [comment]
Hey, I am a little busy with College at the moment.
However, I will test wherever possible. My contribution will be limited and probably wont include much programming.

**Comment by LodeVlaeminck** [comment]
Oké I will add the new Models

**Comment by LodeVlaeminck** [comment]
Models added an tested. Nested Dictionaries worked from the first try !
