### ISSUE TITLE
Retrieving Events Exception (No Events)

### ISSUE THREAD

**Issue by CarlHalstead** [GamingAnonymous/TornCityAPISharp#5]
When there are no events but you still try to deserialize, expecting there to be some. It causes an exception.
```
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Additional information: Exception has been thrown by the target of an invocation.
```

**Comment by LodeVlaeminck** [comment]
I think this error is resolved in the latest build

**Comment by CarlHalstead** [comment]
Ok, I will test soon and close if it is fixed. I am expecting a parcel which is a 2nd monitor, so cannot test just yet.

**Comment by CarlHalstead** [comment]
Tested a little and the exception is no longer caused.
So at the moment I am trying to get a message to display if there are no events. How would I check this?
@LodeVlaeminck I tried
```c#
if (playerEvents.events == null)
{
	Console.WriteLine("You have no events");
	return;
}
```

```c#
if (playerEvents == null)
{
	Console.WriteLine("You have no events");
	return;
}
```
I also tried this one below, but it caused an exception

```c#
if (playerEvents.events.Count <= 0)
{
	Console.WriteLine("You have no events");
	return;
}
```
```
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Additional information: Exception has been thrown by the target of an invocation.
```
I will create a seperate issue.
